"use client"
import './globals.css'
import type { Metadata } from 'next'

import Footer from '@/components/footer/Footer'
import Navbar from '@/components/navbar/Navbar'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#04010E] text-white">

        <Navbar />
        {children}
        <Footer />
      </body>
    </html >
  )
}




